---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sock-shop-monitoring
  namespace: flux-system
spec:
  interval: 30s
  path: ./manifests-monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: sock-shop
  targetNamespace: monitoring

